/**
 * routes.js
 *
 * list of route constants used for navigation
 *
 * @author albert
 * @flow
 */

'use strict';

var routes = {
  MAIN: {
    LOADING: 'MAIN_LOADING',
    TABBAR: 'MAIN_TABBAR',
    NEWPOST: 'MAIN_NEWPOST',
    EDITPOST: 'MAIN_EDITPOST',
    NEWBEVY: 'MAIN_NEWBEVY',
    NEWBOARD: 'MAIN_NEWBOARD',
    COMMENT: 'MAIN_COMMENT',
    PROFILE: 'MAIN_PROFILE',
    BEVYNAV: 'MAIN_BEVYNAV',
    BEVYVIEW: 'BEVY_VIEW',
    SETTINGSVIEW: 'SETTINGS_VIEW',
    MAP: 'MAIN_MAP',
    LOGIN: 'MAIN_LOGIN',
    INVITEUSERS: 'MAIN_INVITEUSERS',
    WEBVIEW: 'MAIN_WEBVIEW',
    FEEDBACK: 'MAIN_FEEDBACK',
    PATCHNOTES: 'MAIN_PATCHNOTES',
  },

  NEWPOST: {
    INPUT: 'NEWPOST_INPUT',
    BOARDPICKER: 'NEWPOST_BOARDPICKER',
    CREATEEVENT: 'NEWPOST_CREATEEVENT',
    DATEPICKER: 'NEWPOST_DATEPICKER',
    TAGPICKER: 'NEWPOST_TAGPICKER'
  },

  LOGIN: {
    LOGIN: 'LOGIN_LOGIN',
    FORGOT: 'LOGIN_FORGOT',
    REGISTER: 'LOGIN_REGISTER',
    LOADINGLOGIN: 'LOGIN_LOADING_LOGIN',
    SLUG: 'LOGIN_SLUG',
    INTRO: 'LOGIN_INTRO'
  },

  BEVY: {
    BEVYVIEW: 'BEVY_BEVYVIEW',
    INFO: 'BEVY_INFO',
    SETTINGS: 'BEVY_SETTINGS',
    MYBEVIES: 'BEVY_MYBEVIES',
    BOARDSETTINGS: 'BEVY_BOARDSETTINGS',
    BOARDINFO: 'BEVY_BOARDINFO'
  },

  PROFILE: {
    USER: 'PROFILE_USER'
  }
};

module.exports = routes;
