/**
 * routes.js
 *
 * list of route constants used for navigation
 *
 * @author albert
 * @flow
 */

'use strict';

var routes = {
  MAIN: {
    LOADING: 'MAIN_LOADING',
    NEWPOST: 'MAIN_NEWPOST',
    EDITPOST: 'MAIN_EDITPOST',
    NEWBOARD: 'MAIN_NEWBOARD',
    COMMENT: 'MAIN_COMMENT',
    PROFILE: 'MAIN_PROFILE',
    BEVY: 'MAIN_BEVY',
    BEVYSETTINGS: 'MAIN_BEVYSETTINGS',
    BOARDSETTINGS: 'MAIN_BOARDSETTINGS',
    SETTINGSVIEW: 'MAIN_SETTINGSVIEW',
    MAP: 'MAIN_MAP',
    LOGIN: 'MAIN_LOGIN',
    WEBVIEW: 'MAIN_WEBVIEW',
    FEEDBACK: 'MAIN_FEEDBACK',
    PATCHNOTES: 'MAIN_PATCHNOTES',
    DIRECTORY: 'MAIN_DIRECTORY'
  },

  NEWPOST: {
    INPUT: 'NEWPOST_INPUT',
    BOARDPICKER: 'NEWPOST_BOARDPICKER'
  },

  LOGIN: {
    LOGIN: 'LOGIN_LOGIN',
    FORGOT: 'LOGIN_FORGOT',
    REGISTER: 'LOGIN_REGISTER',
    LOADINGLOGIN: 'LOGIN_LOADING_LOGIN',
    SLUG: 'LOGIN_SLUG',
    INTRO: 'LOGIN_INTRO'
  },

  BEVY: {
    BEVYVIEW: 'BEVY_BEVYVIEW',
    INFO: 'BEVY_INFO',
    SETTINGS: 'BEVY_SETTINGS',
    BOARDSETTINGS: 'BEVY_BOARDSETTINGS',
    BOARDINFO: 'BEVY_BOARDINFO'
  },

  PROFILE: {
    USER: 'PROFILE_USER'
  }
};

module.exports = routes;
